### ISSUE TITLE
IPython notebook output formatting

### ISSUE THREAD

**Issue by dfroger** [pmorissette/klink#5]
I' m  trying to build klink documentation:

    cd klink
    make html

I get warnings about `intro.rst` and `nb-examples.rst` not included in any toctree, and `favicon.ico` not existing.

Notebook output (for example, `this is a printed line` in the  [doc](http://pmorissette.github.io/klink/examples.html#ipython-notebook) ) is displayed as a IPython cell (in a blank rounded rectangle).

The generated example.html contains:

    <div class="pynb-result highlight-python"><div class="highlight"><pre>this is a printed line

So there is the `pynb-result` tag, but it seems the CSS rule is not applied correctly.

My `Sphinx` version is `1.3.1`.

**Comment by dfroger** [comment]
Seems that the problem come from the `<div class="highlight">` that shoud not be here.

I'll investigate in the day.

**Comment by pmorissette** [comment]
Hey @dfroger,

Thanks for the heads up. To be honest, haven't looked at this project in a while. I just cloned the source on a new box and I am getting the same errors as you. I will look into it and report back. 

Cheers,
Phil

**Comment by pmorissette** [comment]
c749de9 includes some css hacks to fix the issue. Not sure why the div.highlight is getting injected now and wasn't before.

If you can find a better solution, please let me know!

Cheers,
Phil

**Comment by dfroger** [comment]
Thanks a lot! I don't understand either why div.heighlight is injected, I tried to prevent it, but it seems difficult.

I like the CSS solution!

This motivates me to improve my poor CSS skills...

**Comment by pmorissette** [comment]
Haha yeah it's kind of a hack but it works!
