### ISSUE TITLE
Missing table of content in klink documentation

### ISSUE THREAD

**Issue by dfroger** [pmorissette/klink#6]
I' m  trying to build klink documentation:

    cd klink
    make html

I get warnings about `intro.rst` and `nb-examples.rst` not included in any toctree, and `favicon.ico` not existing.

The table of content that should be in the left, between logo and Github link, is not displayed.

My `Sphinx` version is `1.3.1`.

**Comment by pmorissette** [comment]
This was fixed with c749de9

http://stackoverflow.com/questions/17194400/sphinx-toctree-either-displays-a-toc-in-sidebar-with-bulleted-list-in-body-or-n

Warnings are still present but sidebar works.

Cheers,
Phil

**Comment by dfroger** [comment]
Great thanks for the fix!
